volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes: 
      - pg_data_production:/var/lib/postgresql/data
  
  backend:
    image: firuzdadabaev/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
  
  frontend:
    env_file: .env
    image: firuzdadabaev/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: firuzdadabaev/taski_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
    ports:
      - 8000:80
    depends_on:
      - backend